找出最大值、最小值，或其索引位置。

In [2]:
import numpy as np
a=np.amax(np.array([1,2,3,2,1]))
a

3

In [3]:
arr=np.array([1,2,3,4]).reshape(2,2)
np.amax(arr,axis=0)
np.amax(arr,axis=1)

array([2, 4])

In [4]:
arr=np.random.randint(30,size=(2,3,5))
arr.max(axis=0)
arr.max(axis=1)
arr.max(axis=2)

array([[29, 21, 26],
       [24, 27, 18]])

In [5]:
arr.min(axis=0)
np.amin(arr,axis=0)


array([[ 1,  3, 15, 13,  8],
       [17, 15,  8,  4, 17],
       [ 2,  2,  4,  8, 17]])

In [6]:
np.argmax(arr,axis=None)
np.argmin(arr,axis=None)
arr.argmax(axis=0)
arr.argmax(axis=1)
arr.argmax(axis=2)
arr.argmin(axis=0)
arr.argmin(axis=1)
arr.argmin(axis=2)

array([[1, 3, 3],
       [0, 3, 0]], dtype=int64)

轉置矩陣

In [14]:
a=np.arange(12).reshape(3,4)
a
a=np.transpose(a)#轉置矩陣
a
a=a.transpose()#轉置矩陣
a
a=a.T#轉置矩陣
a

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

排序

In [18]:
a=np.random.randint(100,size=20)
b=np.sort(a)
b
b=np.argsort(a)#傳回索引排序而不是值的排序
b


array([ 8, 17,  5,  6,  0,  7, 12,  2, 19, 10, 14,  1, 13,  3, 11, 18, 16,
        4,  9, 15], dtype=int64)

In [23]:
value=[('Alice',25,9.7),('Bob',12,7.6),('Casser',1,8.6),('David',10,7.6)]
dt=[('name','S10'),('ID',int),('score',float)]
a=np.array(value,dtype=dt)
a
a=np.sort(a,order='score')
a

array([(b'Bob', 12, 7.6), (b'David', 10, 7.6), (b'Casser',  1, 8.6),
       (b'Alice', 25, 9.7)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

陣列合併

In [26]:
a=np.arange(12)
b=np.arange(5)
c=np.hstack((a,b))
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1])

In [29]:
a=np.arange(4).reshape(2,2)
b=np.arange(5)
c=np.hstack((a,b))
c
#會出現Error

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [30]:
c=np.arange(4).reshape(2,2)
d=np.arange(6).reshape(2,3)
np.hstack((c,d))
#以第一軸為主合併

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5]])

In [32]:
e=np.arange(12).reshape(2,2,3)
f=np.arange(6).reshape(2,1,3)
np.hstack((e,f))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[ 6,  7,  8],
        [ 9, 10, 11],
        [ 3,  4,  5]]])

In [ ]:
a=np.arange(12).reshape(-1,1)
b=np.arange(2).reshape(-1,1)
c=np.arange(2).reshape(1,2)
d=np.arange(4).reshape(2,2)
np.vstack((c,d))