In [1]:
import numpy as np
a=np.amax(np.array([1,2,3,2,1]))
a

3

In [5]:
arr=np.array([1,2,3,4]).reshape(2,2)
np.amax(arr,axis=0)
np.amax(arr,axis=1)

array([3, 4])

In [18]:
arr=np.random.randint(30,size=(2,3,5))
arr.max(axis=0)
arr.max(axis=1)
arr.max(axis=2)

array([[25, 16, 28],
       [24, 28, 23]])

In [20]:
arr.min(axis=0)
np.amin(arr,axis=0)


array([[ 1,  1, 10,  6, 20],
       [15,  9,  9, 16,  4],
       [ 8,  4,  9,  3, 12]])

In [29]:
np.argmax(arr,axis=None)
np.argmin(arr,axis=None)
arr.argmax(axis=0)
arr.argmax(axis=1)
arr.argmax(axis=2)
arr.argmin(axis=0)
arr.argmin(axis=1)
arr.argmin(axis=2)

array([[1, 4, 1],
       [0, 4, 3]], dtype=int64)